---
title: "R Notebook"
output: html_notebook
---




$$
\text{arrivals}_{predicted} = \text{arrivals}_{May2020} + 20\% \times (\text{arrivals}_{August2019}-\text{arrivals}_{May2020}) 
$$

```{r}
library(magrittr)
jh_cases_recovered<-readr::read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
jh_cases_recovered$EventType<-"Recoveries"
jh_cases_confirmed <- readr::read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
jh_cases_confirmed$EventType<-"CasesConfirmed"
jh_deaths<-readr::read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

separate_australian_states <- TRUE

jh_deaths$EventType<-"Deaths"
jh_data<-rbind(jh_cases_confirmed,jh_cases_recovered,jh_deaths)

if (separate_australian_states){
  jh_data %<>% 
  mutate(SelectedTerritory = 
           ifelse(`Country/Region`=="Australia",
                  paste0(`Province/State`,", ",`Country/Region`),
                  `Country/Region`),
         .before=`Province/State`)
}else{
  jh_data %<>% 
  mutate(SelectedTerritory = `Country/Region`,
         .before=`Province/State`)
}
jh_bycountry<-jh_data %>% 
  dplyr::select(-Lat,-Long,-`Province/State`,-`Country/Region`) %>% 
  group_by(SelectedTerritory,EventType) %>% summarise_all(sum,na.rm=TRUE)

jh_bycountry

```



```{r}
jh_bycountry_activecases <- cbind(
  jh_bycountry %>% arrange(SelectedTerritory) %>% filter(EventType=="CasesConfirmed") %>% .$SelectedTerritory,
  "ActiveCases",
  jh_bycountry %>% arrange(SelectedTerritory) %>% filter(EventType=="CasesConfirmed") %>% .[,3:ncol(.)] - 
    jh_bycountry %>% arrange(SelectedTerritory) %>% filter(EventType=="Deaths") %>% .[,3:ncol(.)] -
    jh_bycountry %>% arrange(SelectedTerritory) %>% filter(EventType=="Recoveries") %>% .[,3:ncol(.)]
)
colnames(jh_bycountry_activecases)[1:2] <- c("SelectedTerritory","EventType")


View(jh_bycountry_activecases[,c(1:2,120:ncol(jh_bycountry_activecases))])

```

## read from google sheets

```{r}
library(googlesheets4)
gs4_deauth()
manual_corrections<-read_sheet("1hkpfinHpxT1KcTI8umh55aaiFug12jKKSMZoae4ttlA")

```










```{r}
#can we output the actual active cases for new zealand?

library(DT)
source("utils.R")
source("simulation.R")
source("country_classification_rules.R")
library(ggrepel)

life_exp_thresh <- 70
default_assumed_ifr_percent<-0.6
default_quarantine_failure_odds<-12
default_assumed_sensitivity <- 0.3
default_general_travel_rate <- 0.2

run_date<-Sys.Date()
month_name <- format(run_date,"%B")

nogeo_world_basic_data <- get_geomapped_covid_data(life_exp_thresh,run_date,separate_aussie_states_and_hk = TRUE,include_geo_data = FALSE)
covid_data <- get_analysis_covid_data(
      nogeo_world_basic_data,
      screening_sensitivity = 0.5,
      quarantine_odds_override=1/12,
      general_travel_rate = 0.2,
      assumed_ifr = 0.0065)

#and now get the new zealand data

covid_data %>% filter(Location=="New Zealand") %>% t %>% View
```
